[package]
name = "path_planning"
version = "0.1.0"
authors = ["David Lundell <david.lundell@trioptima.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"

[profile.dev]
opt-level = 1
